# Page settings

baseURL = "https://mazzutti.github.io/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[minify]
    disableCSS = true
    [minify.tdewolff]
    [minify.tdewolff.css]
    keepCSS2 = true

[params]
    author = "mazzutti"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Tiago Mazzutti"
        tagline = "Software Engineer"
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "Brazil"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+55 049 988 386 214"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "tiagomzt@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.linkedin.com/in/mazzutti"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Dart"
        [[params.skills.list.items]]
        details = "Flutter"
        [[params.skills.list.items]]
        details = "JavaScript"
        [[params.skills.list.items]]
        details = "C++"
        [[params.skills.list.items]]
        details = "Java"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "Go"
        [[params.skills.list.items]]
        details = "Matlab"
        [[params.skills.list.items]]
        details = "Typescript"
        [[params.skills.list.items]]
        details = "ReactJS"
        [[params.skills.list.items]]
        details = "Vue"
        [[params.skills.list.items]]
        details = "Angular"
        [[params.skills.list.items]]
        details = "NodeJS"
        [[params.skills.list.items]]
        details = "Software Development"
        [[params.skills.list.items]]
        details = "Data Structures"
        [[params.skills.list.items]]
        details = "Strong Programming Skills"
        [[params.skills.list.items]]
        details = "Engineering"
        [[params.skills.list.items]]
        details = "Algorithms"
        [[params.skills.list.items]]
        details = "Graph Theory"
        [[params.skills.list.items]]
        details = "Computer Science"
        [[params.skills.list.items]]
        details = "Computer Programming"
        [[params.skills.list.items]]
        details = "Test Automation"
        [[params.skills.list.items]]
        details = "Software Design"
        [[params.skills.list.items]]
        details = "Agile Methodologies"
        [[params.skills.list.items]]
        details = "Web Applications"
        [[params.skills.list.items]]
        details = "Representational State Transfer (REST)"
        [[params.skills.list.items]]
        details = " Back-End Web Development"
        [[params.skills.list.items]]
        details = "Scrapy"
        [[params.skills.list.items]]
        details = "Jupyter notebook"
        [[params.skills.list.items]]
        details = "Artificial Intelligence."
        separator = ""
        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Adaptability"
        [[params.skills.list.items]]
        details = "Good Time management"
        [[params.skills.list.items]]
        details = "Collaboration"
        [[params.skills.list.items]]
        details = "Teamwork"
        [[params.skills.list.items]]
        details = "Communication"
        [[params.skills.list.items]]
        details = "Teamwork"
        [[params.skills.list.items]]
        details = "Creativity"
        [[params.skills.list.items]]
        details = "Diversity & Inclusion"
        [[params.skills.list.items]]
        details = "Empathy"
        [[params.skills.list.items]]
        details = "Work ethic"
        [[params.skills.list.items]]
        details = "Presentation Skills"
        [[params.skills.list.items]]
        details = "Interpersonal Skills"
        [[params.skills.list.items]]
        details = "Analytical Skills"
        [[params.skills.list.items]]
        details = "Decision-Making"
        [[params.skills.list.items]]
        details = "Problem Solver"
        [[params.skills.list.items]]
        details = "Flexibility"
        [[params.skills.list.items]]
        details = "Willingness to learn"
        [[params.skills.list.items]]
        details = "Positive attitude"
        [[params.skills.list.items]]
        details = "Attention to detail."
        separator = ""

    [params.education]
        enable = true
        [[params.education.list]]
        degree = "Doctor of Science (Ph.D.) - Computer Science"
        university = "[Universidade Federal de Santa Catarina - Brazil](https://ppgcc.ufsc.br/apresentacao/?lang=en)"
        dates = "2015 - 2019"
        details = "Research focused in Artificial Neural Networks, Fuzzy Logic and Evolutionary Computing, that led to advances in Computational Intelligence and Machine Learning techniques."
        grade =  "4.0 out of 4.0"
        [[params.education.list]]
        degree = "Master of Science (M.Sc.) - Computer Science"
        university = "[Universidade Federal de Santa Catarina - Brazil](https://ppgcc.ufsc.br/apresentacao/?lang=en)"
        dates = "2009 - 2011"
        details = "Research focused on Multi-Agent Systems."
        grade = "4.0 out of 4.0"
        [[params.education.list]]
        degree = "Bachelor of Science (B.Sc.) - Computer Science"
        university = "[Universidade Federal de Santa Catarina - Brazil](https://cco.ufsc.br/?lang=en)"
        dates = "2005 - 2009"
        details = "As an intern, I took part in the construction of ERP systems, among other projects."
        grade = "8.07 out of 10.0"

    [params.awards]
        enable = false
        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"


    [params.languages]
        enable = true
        [[params.languages.list]]
        name = "Portuguese"
        level = "Native or bilingual proficiency"
        [[params.languages.list]]
        name = "English"
        level = "Full professional proficiency"

    [params.interests]
        enable = true
        [[params.interests.list]]
        name = "Science Fiction Movies"
        [[params.interests.list]]
        name = "Space Exploration"
        [[params.interests.list]]
        name = "Fishing"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Learning Programming Languages"
        [[params.interests.list]]
        name = "Programming Computers."
        separator = ""

    [params.summary]
        enable = true
        objective = "I'm seeking a challenging Software Engineer position in a reputed organization where I can use my knowledge and skills, leverage my learnings and contribute to the organization’s growth."
        about = "Enthusiastic and experienced teacher with 10+ years of experience in topics like programming, algorithm design, mobile and web development, data structures and OOP. I'm also a PhD in Computer Science, completely passionate about programming languages and building software solutions with a positive impact in society."

    [params.experience]
        enable = true
        [[params.experience.list]]
        title = "Full Professor"
        dates = "2011 - Present"
        company = "Instituto Federal Catarinese - Brazil"
        details = "As I finished my Master's Degree, I started to work as a full time computer science professor. The main activities I have been doing are:"
        [[params.experience.list.items]]
        details = "I have taught subjects such as Computational Thinking, Computer Programming, Algorithm Design, Data Structures, Frontend/Backend and Mobile Development."
        [[params.experience.list.items]]
        details = "In a practical and effective way, I have been applying technologies such as Python, Javascript, C++, TypeScript, Dart, Flutter, HTML, CSS, git, LaTex and Linux to teaching, research and project development."
        [[params.experience.list.items]]
        details = "As a member of many cross-functional and interdisciplinary institutional teams, I've been working collaboratively either in person or remotely, employing interpersonal communication skills to design, deploy and manage diverse courses for hundreds of students from different backgrounds."
        [[params.experience.list.items]]
        details = "I have been developing and managing learning objectives for several students, guiding them in forming original interpretive arguments based on primary and secondary sources and evidence."
        [[params.experience.list.items]]
        details = "I have presented complex ideas through the synthesis and effective communication of data, to diverse audiences with varying degrees of familiarity with the subject matter."
        [[params.experience.list.items]]
        details = "I have been learning continuously and effectively, keeping up with technological advances, teaching students with a curriculum suited to the current demands of the job market."

        [[params.experience.list]]
        title = "Postgraduate Distance Learning Coordinator"
        dates = "2015 - 2016"
        company = "Instituto Federal Catarinese - Brazil"
        details = "I was responsible mainly for timimg, course crew and the physical resources management, besides guaranteeing normal functioning of teaching and practical classes activities."

        [[params.experience.list]]
        title = "Technical Course in Computer Science Coordinator"
        dates = "2013 - 2015"
        company = "Instituto Federal Catarinese - Brazil"
        details = "I was responsible mainly for timimg, course crew and the physical resources management, besides guaranteeing normal functioning of teaching and practical classes activities."


        [[params.experience.list]]
        title = "Researcher/Developer"
        dates = "2009 - 2011"
        company = "IATE – Inteligência Artificial e Tecnologia Educacional – UFSC – Brazil"
        details = "I developed AI tools based on Multi-Agent systems and other techniques of Symbolic AI."

        [[params.experience.list]]
        title = "Researcher/Developer"
        dates = "2006 - 2009"
        company = "Instituto Federal Catarinese - Brazil"
        details = "As a member of the [PET](https://petcomputacao.ufsc.br/) program, I've written course material for C/C++, Python, Linux, LaTeX, etc, presented seminars and short courses and organized committees for Computer Science events and academic weeks."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "SO-BR v2"
        company = "UFSC – Brazil"
        dates = "(Jan 2015 - Jan 2018)"
        tagline = "Real-time decision support software for oil well drilling processes, developed mainly with C++ and Qt. This software has been applied successfully to challenging problems such as oil prospecting, modeling, planning, optimization and risk analysis in drilling wells and the characterization of oil reservoirs."

        [[params.projects.list]]
        title = "antlr4dart"
        dates = "(Jan 2014 - Aug 2014)"
        company = "Open Source"
        tagline = "Just for fun, I created a complete Dartlang port/implementation of the ANTLR parser generator. It includes also the Dart version of the ANTLR runtime library. The source code is open source and available on my Github."
        ext_link = "https://github.com/mazzutti/antlr4dart"

    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "Adaptive missing data imputation with incremental Neuro-Fuzzy gaussian mixture network (INFGMN)"
        journal = "International Joint Conference on Neural Networks (IJCNN) - IEEE Xplore · Oct 15, 2018"
        ext_link = "https://doi.org/10.1109/IJCNN.2018.8489515"
        [[params.information.list.items]]
        details = "INFGMN – Incremental Neuro-Fuzzy Gaussian mixture network"
        journal = "Expert Systems with Applications - Elsevier · Dec 15, 2017"
        ext_link = "https://doi.org/10.1016/j.eswa.2017.07.032"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/mazzutti"
        title = ""
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/mazzutti"
        title = ""
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = ""

    [params.footer]
        enable = true
        copyright = "Tiago Mazzutti | Ported from [Cowbosmall](//github.com/cowboysmall-tools/hugo-devresume-theme.git)"
